name: Build and Push to ACR

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to ACR
        uses: aliyun/acr-login@v1
        with:
          login-server: https://crpi-hhhd1ym0vn8x5l6u.cn-shanghai.personal.cr.aliyuncs.com
          username: "${{ secrets.ACR_USERNAME }}"
          password: "${{ secrets.ACR_PASSWORD }}"

      - name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: crpi-hhhd1ym0vn8x5l6u.cn-shanghai.personal.cr.aliyuncs.com/mille/videoanalysis:latest
